/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

// ============================================================================
// ⚠️  GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by the code generator.
// Any manual changes will be overwritten when the generator runs.
// To modify this file, update the templates in codegen/templates/
// ============================================================================

import { type AbstractSession, ImperativeError, ImperativeExpect, Logger } from "@zowe/imperative";
import { CicsCmciConstants } from "../constants";
import type { ICMCIApiResponse, ILibraryParms } from "../doc";
import { performAction } from "../utils/ResourceActions";

/**
 * Disabling a library in CICS
 * @param {AbstractSession} session - the session to connect to CMCI with
 * @param { ILibraryParms } parms - parameters for disabling the library
 * @param {string} parms.name - the name of the library to disable (1-8 characters)
 * @param {string} parms.regionName - the CICS region name
 * @param {string} [parms.cicsPlex] - the CICSPlex name (optional)
 * @param {string} [parms.busy] - busy condition option: "WAIT", "NOWAIT", or "FORCE" (case-insensitive, optional, default: "WAIT")
 * @returns {Promise<ICMCIApiResponse>} promise that resolves to the response
 * @throws {ImperativeError} CICS library name not defined, blank, or exceeds maximum length
 * @throws {ImperativeError} CICS region name not defined or blank
 * @throws {ImperativeError} Invalid BUSY parameter value
 * @throws {ImperativeError} CicsCmciRestClient request fails
 */
export async function disableLibrary(session: AbstractSession, parms: ILibraryParms): Promise<ICMCIApiResponse> {
  // Validate required parameters
  ImperativeExpect.toBeDefinedAndNonBlank(parms.name, "CICS Library name", "CICS library name is required");
  ImperativeExpect.toBeDefinedAndNonBlank(parms.regionName, "CICS Region name", "CICS region name is required");

  // Validate library name length (CICS resource names are limited to 8 characters)
  if (parms.name.length > 8) {
    throw new ImperativeError({
      msg: `CICS library name "${parms.name}" exceeds maximum length of 8 characters`,
    });
  }

  Logger.getAppLogger().debug(
    `Attempting to disable a library with the following parameters:\n%s`,
    JSON.stringify(parms)
  );

  // Get busy parameter value
  const busyValue = parms.busy ? parms.busy.trim().toUpperCase() : "WAIT";

  // Validate busy parameter
  if (!CicsCmciConstants.CICS_BUSY_VALUES.includes(busyValue)) {
    const allowedValuesStr = CicsCmciConstants.CICS_BUSY_VALUES.join(", ");
    throw new ImperativeError({
      msg: `Invalid BUSY parameter value: "${ busyValue}". Must be one of: ${allowedValuesStr}`,
    });
  }

  // Use generic performAction utility
  return performAction(
    session,
    CicsCmciConstants.CICS_CMCI_LIBRARY,
    "DISABLE",
    {
      name: parms.name,
      regionName: parms.regionName,
      cicsPlex: parms.cicsPlex,
    },
    CicsCmciConstants.CICS_LIBRARY_CRITERIA_FIELD,
    { name: "BUSY", value: busyValue }
  );
}

/**
 * Enabling a library in CICS
 * @param {AbstractSession} session - the session to connect to CMCI with
 * @param { ILibraryParms } parms - parameters for enabling the library
 * @param {string} parms.name - the name of the library to enable (1-8 characters)
 * @param {string} parms.regionName - the CICS region name
 * @param {string} [parms.cicsPlex] - the CICSPlex name (optional)
 * @returns {Promise<ICMCIApiResponse>} promise that resolves to the response
 * @throws {ImperativeError} CICS library name not defined, blank, or exceeds maximum length
 * @throws {ImperativeError} CICS region name not defined or blank
 * @throws {ImperativeError} CicsCmciRestClient request fails
 */
export async function enableLibrary(session: AbstractSession, parms: ILibraryParms): Promise<ICMCIApiResponse> {
  // Validate required parameters
  ImperativeExpect.toBeDefinedAndNonBlank(parms.name, "CICS Library name", "CICS library name is required");
  ImperativeExpect.toBeDefinedAndNonBlank(parms.regionName, "CICS Region name", "CICS region name is required");

  // Validate library name length (CICS resource names are limited to 8 characters)
  if (parms.name.length > 8) {
    throw new ImperativeError({
      msg: `CICS library name "${parms.name}" exceeds maximum length of 8 characters`,
    });
  }

  Logger.getAppLogger().debug(
    `Attempting to enable a library with the following parameters:\n%s`,
    JSON.stringify(parms)
  );

  // Use generic performAction utility (no additional parameters needed for ENABLE)
  return performAction(
    session,
    CicsCmciConstants.CICS_CMCI_LIBRARY,
    "ENABLE",
    {
      name: parms.name,
      regionName: parms.regionName,
      cicsPlex: parms.cicsPlex,
    },
    CicsCmciConstants.CICS_LIBRARY_CRITERIA_FIELD
  );
}

