/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

// ============================================================================
// ⚠️  GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by the code generator.
// Template: codegen/templates/tests/sdk.resource.unit.test.hbs
// Any manual changes will be overwritten when the generator runs.
// ============================================================================

import { Session } from "@zowe/imperative";
import {
  CicsCmciConstants,
  CicsCmciRestClient,
  enableLibrary,
  type ICMCIApiResponse,
  type ILibraryParms,
} from "../../../src";

describe("CMCI - Enable library", () => {
  const library = "TESTFILE";
  const region = "region";
  const content = "ThisIsATest" as unknown as ICMCIApiResponse;

  const enableParms: ILibraryParms = {
    regionName: region,
    name: library,
  };

  const dummySession = new Session({
    user: "testuser",
    password: "testpass",
    hostname: "test.cics.host.com",
    port: 1490,
  });

  let error: any;
  let response: any;
  let endPoint: any;
  let requestBody: any;

  describe("validation", () => {
    beforeEach(() => {
      response = undefined;
      error = undefined;
      enableParms.regionName = region;
      enableParms.name = library;
    });

    it("should throw an error if no region name is specified", async () => {
      (enableParms as any).regionName = undefined;
      try {
        response = await enableLibrary(dummySession, enableParms);
      } catch (err) {
        error = err;
      }
      expect(response).toBeUndefined();
      expect(error).toBeDefined();
      expect(error.message).toContain("CICS region name is required");
    });

    it("should throw an error if no library name is specified", async () => {
      (enableParms as any).name = undefined;
      try {
        response = await enableLibrary(dummySession, enableParms);
      } catch (err) {
        error = err;
      }
      expect(response).toBeUndefined();
      expect(error).toBeDefined();
      expect(error.message).toContain("CICS library name is required");
    });

    it("should throw an error if library name exceeds maximum length", async () => {
      enableParms.name = "TOOLONGNAME";
      try {
        response = await enableLibrary(dummySession, enableParms);
      } catch (err) {
        error = err;
      }
      expect(response).toBeUndefined();
      expect(error).toBeDefined();
      expect(error.message).toContain("exceeds maximum length");
      expect(error.message).toContain("8 characters");
    });
  });

  describe("success scenarios", () => {
    const enableSpy = jest.spyOn(CicsCmciRestClient, "putExpectParsedXml").mockResolvedValue(content);

    beforeEach(() => {
      response = undefined;
      error = undefined;
      enableSpy.mockClear();
      enableSpy.mockResolvedValue(content);
      enableParms.regionName = region;
      enableParms.name = library;
    });

    it("should be able to enable a library", async () => {
      endPoint =
        "/" +
        CicsCmciConstants.CICS_SYSTEM_MANAGEMENT +
        "/" +
        CicsCmciConstants.CICS_CMCI_LIBRARY +
        "/" +
        region +
        `?CRITERIA=(library%3D${ enableParms.name})`;
      requestBody = {
        request: {
          action: {
            $: {
              name: "ENABLE",
            },
          },
        },
      };

      response = await enableLibrary(dummySession, enableParms);
      expect(response).toContain(content);
      expect(enableSpy).toHaveBeenCalledWith(dummySession, endPoint, [], requestBody);
    });
  });
});