/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

// ============================================================================
// ⚠️  GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by the code generator.
// Template: codegen/templates/sdk/utils.resourceactions.hbs
// Any manual changes will be overwritten when the generator runs.
// ============================================================================

import type { AbstractSession } from "@zowe/imperative";
import { CicsCmciRestClient } from "../rest";
import type { ICMCIApiResponse } from "../doc/ICMCIApiResponse";
import type { IGetResourceUriOptions } from "../doc/IGetResourceUriOptions";
import { Utils } from "./Utils";

/**
 * Base parameters for resource actions
 */
export interface IResourceActionParms {
  /** The name of the resource */
  name: string;
  /** The CICS region name */
  regionName: string;
  /** The CICSPlex name (optional) */
  cicsPlex?: string;
  /** The CSD group name (optional) */
  csdGroup?: string;
}

/**
 * Performs a generic action on a CICS resource
 * @param session - The CMCI session
 * @param resourceType - The CMCI resource type (e.g., "CICSLocalFile")
 * @param action - The action to perform (e.g., "CLOSE", "OPEN")
 * @param params - The resource parameters
 * @param criteriaField - The resource selection criteria field (e.g., "FILE")
 * @param additionalParams - Additional action-specific parameters (e.g., { name: "BUSY", value: "WAIT" })
 * @returns The CMCI API response
 */
export async function performAction(
  session: AbstractSession,
  resourceType: string,
  action: string,
  params: IResourceActionParms,
  criteriaField: string,
  additionalParams?: { name: string; value: string }
): Promise<ICMCIApiResponse> {
  // Build CMCI resource URI using the existing Utils helper
  const options: IGetResourceUriOptions = {
    cicsPlex: params.cicsPlex,
    regionName: params.regionName,
    criteria: `${criteriaField}=${params.name}`,
  };

  const cmciResource = Utils.getResourceUri(resourceType, options);

  // Build request body
  const requestBody: any = {
    request: {
      action: {
        $: {
          name: action,
        },
      },
    },
  };

  // Add additional parameters if provided
  if (additionalParams) {
    requestBody.request.action.parameter = {
      $: additionalParams,
    };
  }

  return CicsCmciRestClient.putExpectParsedXml(session, cmciResource, [], requestBody);
}

/**
 * Performs an attribute-update action on a CICS resource (e.g. setting ENABLESTATUS on a URIMap).
 * This is used by resources whose enable/disable operations set an attribute rather than
 * invoking a named CMCI action command.
 * @param session - The CMCI session
 * @param resourceType - The CMCI resource type (e.g., "CICSURIMap")
 * @param params - The resource parameters
 * @param criteriaField - The resource selection criteria field (e.g., "NAME")
 * @param attributeField - The CMCI attribute name to update (e.g., "ENABLESTATUS")
 * @param attributeValue - The value to set (e.g., "ENABLED", "DISABLED")
 * @returns The CMCI API response
 */
export async function performAttributeUpdate(
  session: AbstractSession,
  resourceType: string,
  params: IResourceActionParms,
  criteriaField: string,
  attributeField: string,
  attributeValue: string
): Promise<ICMCIApiResponse> {
  const options: IGetResourceUriOptions = {
    cicsPlex: params.cicsPlex,
    regionName: params.regionName,
    criteria: `${criteriaField}=${params.name}`,
  };

  const cmciResource = Utils.getResourceUri(resourceType, options);

  const requestBody: any = {
    request: {
      update: {
        attributes: {
          $: {
            [attributeField]: attributeValue,
          },
        },
      },
    },
  };

  return CicsCmciRestClient.putExpectParsedXml(session, cmciResource, [], requestBody);
}

