/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

// ============================================================================
// ⚠️  GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by the code generator.
// Template: codegen/templates/cli/resource.definition.hbs  (covers both Pattern A and Pattern B)
// Any manual changes will be overwritten when the generator runs.
// ============================================================================

import type { ICommandDefinition } from "@zowe/imperative";
import type i18nTypings from "../../-strings-/en";

// Does not use the import in anticipation of some internationalization work to be done later.
const strings = (require("../../-strings-/en").default as typeof i18nTypings).DISABLE.RESOURCES.URIMAP;

/**
 * Urimap command definition for the Disable command group
 */
export const UrimapDefinition: ICommandDefinition = {
  name: "urimap",
  aliases: [],
  description: strings.DESCRIPTION,
  handler: __dirname + "/Urimap.handler",
  type: "command",
  positionals: [
    {
      name: "urimapName",
      description: strings.POSITIONALS.URIMAPNAME,
      type: "string",
      required: true,
    },
  ],
  options: [
    {
      name: "region-name",
      description: strings.OPTIONS.REGIONNAME,
      type: "string",
    },
    {
      name: "cics-plex",
      description: strings.OPTIONS.CICSPLEX,
      type: "string",
    },
  ],
  profile: { optional: ["cics"] },
  examples: [
    {
      description: strings.EXAMPLES.EX1,
      options: "URIMAPA --region-name MYREGION",
    },
  ],
};
