/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

// ============================================================================
// ⚠️  GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by the code generator.
// Template: codegen/templates/cli/localfile.handler.hbs
// Any manual changes will be overwritten when the generator runs.
// ============================================================================

import {
  closeLocalFile,
  disableLocalFile,
  enableLocalFile,
  openLocalFile,
  type ICMCIApiResponse,
  type ILocalFileParms,
} from "@zowe/cics-for-zowe-sdk";
import { type AbstractSession, type IHandlerParameters, type ITaskWithStatus, TaskStage } from "@zowe/imperative";
import { CicsBaseHandler } from "../CicsBaseHandler";

import type i18nTypings from "../-strings-/en";

// Does not use the import in anticipation of some internationalization work to be done later.
const closeStrings = (require("../-strings-/en").default as typeof i18nTypings).CLOSE.RESOURCES.LOCALFILE;
const disableStrings = (require("../-strings-/en").default as typeof i18nTypings).DISABLE.RESOURCES.LOCALFILE;
const enableStrings = (require("../-strings-/en").default as typeof i18nTypings).ENABLE.RESOURCES.LOCALFILE;
const openStrings = (require("../-strings-/en").default as typeof i18nTypings).OPEN.RESOURCES.LOCALFILE;

type LocalFileAction = "CLOSE" | "DISABLE" | "ENABLE" | "OPEN";

/**
 * Unified command handler for CICS local file operations via CMCI.
 * Determines the action (close/disable/enable/open) based on the command definition's parent.
 *
 * @export
 * @class LocalFileHandler
 * @extends {CicsBaseHandler}
 */
export default class LocalFileHandler extends CicsBaseHandler {
  /**
   * Determines the action type based on the command chain
   * @param {IHandlerParameters} params - Command handler parameters
   * @returns {LocalFileAction} The action type
   */
  private getActionType(params: IHandlerParameters): LocalFileAction {
     const actionMap: Record<string, LocalFileAction> = {
       "close": "CLOSE",
       "disable": "DISABLE",
       "enable": "ENABLE",
       "open": "OPEN",
     };
     const parentCommand = params.definition.parent?.name ?? "";
     if (actionMap[parentCommand]) { return actionMap[parentCommand]; }

     const positionals = params.positionals || [];
     const positionalMatch = positionals.find((p: string) => actionMap[p]);
     if (positionalMatch) { return actionMap[positionalMatch]; }

     const handlerPath = params.definition.handler ?? "";
     const pathMatch = Object.keys(actionMap).find(
       (key) => handlerPath.includes(`/${key}/`) || handlerPath.includes(`\\${key}\\`)
     );
     if (pathMatch) { return actionMap[pathMatch]; }

     // Should not reach here with proper command structure
     throw new Error("Unable to determine action type from command context");
   }

  /**
   * Gets the appropriate strings based on action type
   * @param {LocalFileAction} action - The action type
   * @returns {object} The strings object for the action
   */
  private getStrings(action: LocalFileAction) {
    switch (action) {
      case "CLOSE": return closeStrings;
      case "DISABLE": return disableStrings;
      case "ENABLE": return enableStrings;
      case "OPEN": return openStrings;
    }
  }

  /**
   * Process the command for a CICS local file operation
   * @param {IHandlerParameters} params - Command handler parameters
   * @param {AbstractSession} session - The session to use for the CMCI request
   * @returns {Promise<ICMCIApiResponse>} The CMCI API response
   * @throws {ImperativeError} Various errors from validation or CMCI request failures
   */
  public async processWithSession(params: IHandlerParameters, session: AbstractSession): Promise<ICMCIApiResponse> {
    const action = this.getActionType(params);
    const strings = this.getStrings(action);

    const status: ITaskWithStatus = {
      statusMessage: strings.MESSAGES.PROGRESS,
      percentComplete: 0,
      stageName: TaskStage.IN_PROGRESS,
    };
    params.response.progress.startBar({ task: status });

    // Build parameters for the SDK call
    const sdkParams: ILocalFileParms = {
      name: params.arguments.fileName,
      regionName: params.arguments.regionName,
      cicsPlex: params.arguments.cicsPlex,
    };

    // Add busy parameter only for actions that support it
    const busyActions: LocalFileAction[] = ["CLOSE", "DISABLE"];
    if (busyActions.includes(action) && params.arguments.busy) {
      sdkParams.busy = params.arguments.busy;
    }

    // Call the appropriate SDK function based on action
    let response: ICMCIApiResponse;
    switch (action) {
      case "CLOSE": response = await closeLocalFile(session, sdkParams); break;
      case "DISABLE": response = await disableLocalFile(session, sdkParams); break;
      case "ENABLE": response = await enableLocalFile(session, sdkParams); break;
      case "OPEN": response = await openLocalFile(session, sdkParams); break;
    }

    params.response.console.log(strings.MESSAGES.SUCCESS, params.arguments.fileName);
    return response;
  }
}
