/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

// ============================================================================
// ⚠️  GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by the code generator.
// Template: codegen/templates/cli/localfile.definition.hbs
// Any manual changes will be overwritten when the generator runs.
// ============================================================================

import type { ICommandDefinition } from "@zowe/imperative";
import { CicsCmciConstants } from "@zowe/cics-for-zowe-sdk";
import type i18nTypings from "../../-strings-/en";

// Does not use the import in anticipation of some internationalization work to be done later.
const strings = (require("../../-strings-/en").default as typeof i18nTypings).CLOSE.RESOURCES.LOCALFILE;

/**
 * Local file command definition for the Close command group
 */
export const LocalFileDefinition: ICommandDefinition = {
  name: "CICSLocalFile",
  aliases: ["lf"],
  description: strings.DESCRIPTION,
  handler: __dirname + "/../../common/LocalFileHandler",
  type: "command",
  positionals: [
    {
      name: "fileName",
      description: strings.POSITIONALS.FILENAME,
      type: "string",
      required: true,
    },
  ],
  options: [
    {
      name: "region-name",
      description: strings.OPTIONS.REGIONNAME,
      type: "string",
    },
    {
      name: "cics-plex",
      description: strings.OPTIONS.CICSPLEX,
      type: "string",
    },
    {
      name: "busy",
      description: strings.OPTIONS.BUSY,
      type: "string",
      defaultValue: "WAIT",
      allowableValues: {
        values: [...CicsCmciConstants.CICS_BUSY_VALUES],
        caseSensitive: false,
      },
    },
  ],
  profile: { optional: ["cics"] },
  examples: [
    {
      description: strings.EXAMPLES.EX1,
      options: "TESTFILE --region-name MYREGION",
    },
    {
      description: strings.EXAMPLES.EX2,
      options: "TESTFILE --region-name MYREGION --busy FORCE",
    },
  ],
};
