/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

// ============================================================================
// ⚠️  GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by the code generator.
// Template: codegen/templates/tests/cli.group.definition.unit.test.hbs
// Any manual changes will be overwritten when the generator runs.
// ============================================================================

import type { ICommandDefinition } from "@zowe/imperative";

describe("cics enable", () => {
  const RESOURCES_COUNT = 2;

  it("should not have changed", () => {
    const definition: ICommandDefinition = require("../../../src/enable/Enable.definition");
    expect(definition).toBeDefined();
    expect(definition.children?.length).toBe(RESOURCES_COUNT);
    delete definition.children;
    expect(definition).toMatchSnapshot();
  });
});
