/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

// ============================================================================
// ⚠️  GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by the code generator.
// Template: codegen/templates/sdk/parms.interface.hbs
// Any manual changes will be overwritten when the generator runs.
// ============================================================================

import type { IResourceParms } from "./IResourceParms";

/**
 * Interface for CICS program parameters
 * @export
 * @interface IProgramParms
 * @extends {IResourceParms}
 */
export interface IProgramParms extends IResourceParms {
  /**
   * The CICS CSD Group for resource definition operations.
   * Value will be automatically converted to uppercase
   * @type { string }
   * @memberof IProgramParms
   */
  csdGroup?: string;
}