/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

// ============================================================================
// ⚠️  GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by the code generator.
// Template: codegen/templates/tests/cli.resource.definition.unit.test.hbs
// Any manual changes will be overwritten when the generator runs.
// ============================================================================

import type { ICommandDefinition } from "@zowe/imperative";

describe("cics disable CICSLocalFile", () => {
  it("should not have changed", () => {
    const definition: ICommandDefinition = require("../../../../src/disable/localFile/LocalFile.definition").LocalFileDefinition;
    expect(definition).toBeDefined();
    expect(definition.name).toBe("CICSLocalFile");
    expect(definition.type).toBe("command");
    expect(definition.positionals?.[0].name).toBe("fileName");
    delete definition.handler;
    expect(definition).toMatchSnapshot();
  });
});
